/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as MoreRouteImport } from './routes/more'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as SettingsConnectionRouteImport } from './routes/settings/connection'
import { Route as AccountsCustomersIndexRouteImport } from './routes/accounts/customers/index'
import { Route as AccountsCustomersIdRouteImport } from './routes/accounts/customers/$id'
import { Route as AccountsSuppliersIndexRouteImport } from './routes/accounts/suppliers/index'
import { Route as AccountsSuppliersIdRouteImport } from './routes/accounts/suppliers/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionRoute = SettingsConnectionRouteImport.update({
  id: '/settings/connection',
  path: '/settings/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsCustomersIndexRoute = AccountsCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsCustomersIdRoute = AccountsCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsSuppliersIndexRoute = AccountsSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsSuppliersIdRoute = AccountsSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/items': typeof ItemsRoute
  '/more': typeof MoreRoute
  '/revenue': typeof RevenueRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/accounts/customers/$id': typeof AccountsCustomersIdRoute
  '/accounts/suppliers/$id': typeof AccountsSuppliersIdRoute
  '/accounts/customers/': typeof AccountsCustomersIndexRoute
  '/accounts/suppliers/': typeof AccountsSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/items': typeof ItemsRoute
  '/more': typeof MoreRoute
  '/revenue': typeof RevenueRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/accounts/customers/$id': typeof AccountsCustomersIdRoute
  '/accounts/suppliers/$id': typeof AccountsSuppliersIdRoute
  '/accounts/customers': typeof AccountsCustomersIndexRoute
  '/accounts/suppliers': typeof AccountsSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/items': typeof ItemsRoute
  '/more': typeof MoreRoute
  '/revenue': typeof RevenueRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/accounts/customers/$id': typeof AccountsCustomersIdRoute
  '/accounts/suppliers/$id': typeof AccountsSuppliersIdRoute
  '/accounts/customers/': typeof AccountsCustomersIndexRoute
  '/accounts/suppliers/': typeof AccountsSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/items'
    | '/more'
    | '/revenue'
    | '/settings/connection'
    | '/accounts/customers/$id'
    | '/accounts/suppliers/$id'
    | '/accounts/customers/'
    | '/accounts/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/items'
    | '/more'
    | '/revenue'
    | '/settings/connection'
    | '/accounts/customers/$id'
    | '/accounts/suppliers/$id'
    | '/accounts/customers'
    | '/accounts/suppliers'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/items'
    | '/more'
    | '/revenue'
    | '/settings/connection'
    | '/accounts/customers/$id'
    | '/accounts/suppliers/$id'
    | '/accounts/customers/'
    | '/accounts/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  ItemsRoute: typeof ItemsRoute
  MoreRoute: typeof MoreRoute
  RevenueRoute: typeof RevenueRoute
  SettingsConnectionRoute: typeof SettingsConnectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connection': {
      id: '/settings/connection'
      path: '/settings/connection'
      fullPath: '/settings/connection'
      preLoaderRoute: typeof SettingsConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/customers/': {
      id: '/accounts/customers/'
      path: '/customers'
      fullPath: '/accounts/customers/'
      preLoaderRoute: typeof AccountsCustomersIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/customers/$id': {
      id: '/accounts/customers/$id'
      path: '/customers/$id'
      fullPath: '/accounts/customers/$id'
      preLoaderRoute: typeof AccountsCustomersIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/suppliers/': {
      id: '/accounts/suppliers/'
      path: '/suppliers'
      fullPath: '/accounts/suppliers/'
      preLoaderRoute: typeof AccountsSuppliersIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/suppliers/$id': {
      id: '/accounts/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/accounts/suppliers/$id'
      preLoaderRoute: typeof AccountsSuppliersIdRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsCustomersIdRoute: typeof AccountsCustomersIdRoute
  AccountsSuppliersIdRoute: typeof AccountsSuppliersIdRoute
  AccountsCustomersIndexRoute: typeof AccountsCustomersIndexRoute
  AccountsSuppliersIndexRoute: typeof AccountsSuppliersIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsCustomersIdRoute: AccountsCustomersIdRoute,
  AccountsSuppliersIdRoute: AccountsSuppliersIdRoute,
  AccountsCustomersIndexRoute: AccountsCustomersIndexRoute,
  AccountsSuppliersIndexRoute: AccountsSuppliersIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  ItemsRoute: ItemsRoute,
  MoreRoute: MoreRoute,
  RevenueRoute: RevenueRoute,
  SettingsConnectionRoute: SettingsConnectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
