/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as MoreRouteImport } from './routes/more'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as ItemsExpiryRouteImport } from './routes/items/expiry'
import { Route as ItemsOutOfStockRouteImport } from './routes/items/out-of-stock'
import { Route as ItemsStockRouteImport } from './routes/items/stock'
import { Route as ItemsTrackRouteImport } from './routes/items/track'
import { Route as SettingsConnectionRouteImport } from './routes/settings/connection'
import { Route as TradingIndexRouteImport } from './routes/trading/index'
import { Route as TradingDailyRouteImport } from './routes/trading/daily'
import { Route as TradingItemsRouteImport } from './routes/trading/items'
import { Route as TradingProfitRouteImport } from './routes/trading/profit'
import { Route as AccountsCustomersIndexRouteImport } from './routes/accounts/customers/index'
import { Route as AccountsCustomersIdRouteImport } from './routes/accounts/customers/$id'
import { Route as AccountsSuppliersIndexRouteImport } from './routes/accounts/suppliers/index'
import { Route as AccountsSuppliersIdRouteImport } from './routes/accounts/suppliers/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsExpiryRoute = ItemsExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsOutOfStockRoute = ItemsOutOfStockRouteImport.update({
  id: '/out-of-stock',
  path: '/out-of-stock',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsStockRoute = ItemsStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsTrackRoute = ItemsTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => ItemsRoute,
} as any)
const SettingsConnectionRoute = SettingsConnectionRouteImport.update({
  id: '/settings/connection',
  path: '/settings/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingIndexRoute = TradingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TradingRoute,
} as any)
const TradingDailyRoute = TradingDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => TradingRoute,
} as any)
const TradingItemsRoute = TradingItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => TradingRoute,
} as any)
const TradingProfitRoute = TradingProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => TradingRoute,
} as any)
const AccountsCustomersIndexRoute = AccountsCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsCustomersIdRoute = AccountsCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsSuppliersIndexRoute = AccountsSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsSuppliersIdRoute = AccountsSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/more': typeof MoreRoute
  '/revenue': typeof RevenueRoute
  '/trading': typeof TradingRouteWithChildren
  '/items/expiry': typeof ItemsExpiryRoute
  '/items/out-of-stock': typeof ItemsOutOfStockRoute
  '/items/stock': typeof ItemsStockRoute
  '/items/track': typeof ItemsTrackRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/trading/daily': typeof TradingDailyRoute
  '/trading/items': typeof TradingItemsRoute
  '/trading/profit': typeof TradingProfitRoute
  '/trading/': typeof TradingIndexRoute
  '/accounts/customers/$id': typeof AccountsCustomersIdRoute
  '/accounts/suppliers/$id': typeof AccountsSuppliersIdRoute
  '/accounts/customers/': typeof AccountsCustomersIndexRoute
  '/accounts/suppliers/': typeof AccountsSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/more': typeof MoreRoute
  '/revenue': typeof RevenueRoute
  '/items/expiry': typeof ItemsExpiryRoute
  '/items/out-of-stock': typeof ItemsOutOfStockRoute
  '/items/stock': typeof ItemsStockRoute
  '/items/track': typeof ItemsTrackRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/trading/daily': typeof TradingDailyRoute
  '/trading/items': typeof TradingItemsRoute
  '/trading/profit': typeof TradingProfitRoute
  '/trading': typeof TradingIndexRoute
  '/accounts/customers/$id': typeof AccountsCustomersIdRoute
  '/accounts/suppliers/$id': typeof AccountsSuppliersIdRoute
  '/accounts/customers': typeof AccountsCustomersIndexRoute
  '/accounts/suppliers': typeof AccountsSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/more': typeof MoreRoute
  '/revenue': typeof RevenueRoute
  '/trading': typeof TradingRouteWithChildren
  '/items/expiry': typeof ItemsExpiryRoute
  '/items/out-of-stock': typeof ItemsOutOfStockRoute
  '/items/stock': typeof ItemsStockRoute
  '/items/track': typeof ItemsTrackRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/trading/daily': typeof TradingDailyRoute
  '/trading/items': typeof TradingItemsRoute
  '/trading/profit': typeof TradingProfitRoute
  '/trading/': typeof TradingIndexRoute
  '/accounts/customers/$id': typeof AccountsCustomersIdRoute
  '/accounts/suppliers/$id': typeof AccountsSuppliersIdRoute
  '/accounts/customers/': typeof AccountsCustomersIndexRoute
  '/accounts/suppliers/': typeof AccountsSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/items'
    | '/more'
    | '/revenue'
    | '/trading'
    | '/items/expiry'
    | '/items/out-of-stock'
    | '/items/stock'
    | '/items/track'
    | '/settings/connection'
    | '/trading/daily'
    | '/trading/items'
    | '/trading/profit'
    | '/trading/'
    | '/accounts/customers/$id'
    | '/accounts/suppliers/$id'
    | '/accounts/customers/'
    | '/accounts/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/items'
    | '/more'
    | '/revenue'
    | '/items/expiry'
    | '/items/out-of-stock'
    | '/items/stock'
    | '/items/track'
    | '/settings/connection'
    | '/trading/daily'
    | '/trading/items'
    | '/trading/profit'
    | '/trading'
    | '/accounts/customers/$id'
    | '/accounts/suppliers/$id'
    | '/accounts/customers'
    | '/accounts/suppliers'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/items'
    | '/more'
    | '/revenue'
    | '/trading'
    | '/items/expiry'
    | '/items/out-of-stock'
    | '/items/stock'
    | '/items/track'
    | '/settings/connection'
    | '/trading/daily'
    | '/trading/items'
    | '/trading/profit'
    | '/trading/'
    | '/accounts/customers/$id'
    | '/accounts/suppliers/$id'
    | '/accounts/customers/'
    | '/accounts/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  ItemsRoute: typeof ItemsRouteWithChildren
  MoreRoute: typeof MoreRoute
  RevenueRoute: typeof RevenueRoute
  TradingRoute: typeof TradingRouteWithChildren
  SettingsConnectionRoute: typeof SettingsConnectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/expiry': {
      id: '/items/expiry'
      path: '/expiry'
      fullPath: '/items/expiry'
      preLoaderRoute: typeof ItemsExpiryRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/out-of-stock': {
      id: '/items/out-of-stock'
      path: '/out-of-stock'
      fullPath: '/items/out-of-stock'
      preLoaderRoute: typeof ItemsOutOfStockRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/stock': {
      id: '/items/stock'
      path: '/stock'
      fullPath: '/items/stock'
      preLoaderRoute: typeof ItemsStockRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/track': {
      id: '/items/track'
      path: '/track'
      fullPath: '/items/track'
      preLoaderRoute: typeof ItemsTrackRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/settings/connection': {
      id: '/settings/connection'
      path: '/settings/connection'
      fullPath: '/settings/connection'
      preLoaderRoute: typeof SettingsConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/': {
      id: '/trading/'
      path: '/'
      fullPath: '/trading/'
      preLoaderRoute: typeof TradingIndexRouteImport
      parentRoute: typeof TradingRoute
    }
    '/trading/daily': {
      id: '/trading/daily'
      path: '/daily'
      fullPath: '/trading/daily'
      preLoaderRoute: typeof TradingDailyRouteImport
      parentRoute: typeof TradingRoute
    }
    '/trading/items': {
      id: '/trading/items'
      path: '/items'
      fullPath: '/trading/items'
      preLoaderRoute: typeof TradingItemsRouteImport
      parentRoute: typeof TradingRoute
    }
    '/trading/profit': {
      id: '/trading/profit'
      path: '/profit'
      fullPath: '/trading/profit'
      preLoaderRoute: typeof TradingProfitRouteImport
      parentRoute: typeof TradingRoute
    }
    '/accounts/customers/': {
      id: '/accounts/customers/'
      path: '/customers'
      fullPath: '/accounts/customers/'
      preLoaderRoute: typeof AccountsCustomersIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/customers/$id': {
      id: '/accounts/customers/$id'
      path: '/customers/$id'
      fullPath: '/accounts/customers/$id'
      preLoaderRoute: typeof AccountsCustomersIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/suppliers/': {
      id: '/accounts/suppliers/'
      path: '/suppliers'
      fullPath: '/accounts/suppliers/'
      preLoaderRoute: typeof AccountsSuppliersIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/suppliers/$id': {
      id: '/accounts/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/accounts/suppliers/$id'
      preLoaderRoute: typeof AccountsSuppliersIdRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsCustomersIdRoute: typeof AccountsCustomersIdRoute
  AccountsSuppliersIdRoute: typeof AccountsSuppliersIdRoute
  AccountsCustomersIndexRoute: typeof AccountsCustomersIndexRoute
  AccountsSuppliersIndexRoute: typeof AccountsSuppliersIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsCustomersIdRoute: AccountsCustomersIdRoute,
  AccountsSuppliersIdRoute: AccountsSuppliersIdRoute,
  AccountsCustomersIndexRoute: AccountsCustomersIndexRoute,
  AccountsSuppliersIndexRoute: AccountsSuppliersIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface ItemsRouteChildren {
  ItemsExpiryRoute: typeof ItemsExpiryRoute
  ItemsOutOfStockRoute: typeof ItemsOutOfStockRoute
  ItemsStockRoute: typeof ItemsStockRoute
  ItemsTrackRoute: typeof ItemsTrackRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsExpiryRoute: ItemsExpiryRoute,
  ItemsOutOfStockRoute: ItemsOutOfStockRoute,
  ItemsStockRoute: ItemsStockRoute,
  ItemsTrackRoute: ItemsTrackRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

interface TradingRouteChildren {
  TradingDailyRoute: typeof TradingDailyRoute
  TradingItemsRoute: typeof TradingItemsRoute
  TradingProfitRoute: typeof TradingProfitRoute
  TradingIndexRoute: typeof TradingIndexRoute
}

const TradingRouteChildren: TradingRouteChildren = {
  TradingDailyRoute: TradingDailyRoute,
  TradingItemsRoute: TradingItemsRoute,
  TradingProfitRoute: TradingProfitRoute,
  TradingIndexRoute: TradingIndexRoute,
}

const TradingRouteWithChildren =
  TradingRoute._addFileChildren(TradingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  ItemsRoute: ItemsRouteWithChildren,
  MoreRoute: MoreRoute,
  RevenueRoute: RevenueRoute,
  TradingRoute: TradingRouteWithChildren,
  SettingsConnectionRoute: SettingsConnectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
